fixtures:
  repositories:
    archive:
      repo: "https://github.com/camptocamp/puppet-archive.git"
      ref: "0.3.1"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.1.0"
  symlinks:
    roundcube: "#{source_dir}"

