fixtures:
  forge_modules:
    archive:
      repo: "camptocamp/archive"
      ref: "0.3.1"
    module_data:
      repo: "ripienaar/module_data"
      ref: "0.0.3"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.6.0"
  symlinks:
    roundcube: "#{source_dir}"

