HOSTS:
  debian-8-64:
    roles:
      - master
    platform: debian-8-amd64
    hypervisor: docker
    image: debian:8
    docker_preserve_image: true
    docker_image_commands:
      - 'apt-get update && apt-get -y install cron wget'

CONFIG:
  type: foss
  log_level: info
  trace_limit: 100
